# Generated by Django 4.2.6 on 2023-10-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_vodafone', models.CharField(max_length=20)),
                ('number_kyivstar', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('telegram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('diploma_image', models.ImageField(upload_to='photo_diploma/')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Фото профиля', max_length=20)),
                ('profile_image', models.ImageField(upload_to='photo_profile/')),
            ],
        ),
    ]
