# Generated by Django 4.2.6 on 2023-10-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoprofile',
            name='info_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='photoprofile',
            name='info_uk',
            field=models.TextField(default='', null=True),
        ),
    ]
