# Generated by Django 4.2.6 on 2023-10-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_photoprofile_info_en_photoprofile_info_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomadescription',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomadescription',
            name='title_uk',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
