# Generated by Django 4.2.6 on 2023-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_diplomadescription_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodiploma',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photodiploma',
            name='title_uk',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
