# Generated by Django 4.2.6 on 2023-10-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_photodiploma_title_en_photodiploma_title_uk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoprofile',
            options={'verbose_name_plural': 'Про мене'},
        ),
        migrations.AlterField(
            model_name='photoprofile',
            name='name',
            field=models.CharField(default='Данні профіля', max_length=20),
        ),
    ]
