# Generated by Django 4.2.6 on 2023-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_alter_photodiploma_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Досвід роботи'},
        ),
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.URLField(default='', verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number_kyivstar',
            field=models.CharField(max_length=20, verbose_name='Київстар'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number_vodafone',
            field=models.CharField(max_length=20, verbose_name='Водафон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram',
            field=models.URLField(verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Роботодавець'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Роботодавець'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Роботодавець'),
        ),
    ]
