# Generated by Django 4.2.6 on 2023-10-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='academy_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Назва Академії'),
        ),
        migrations.AddField(
            model_name='education',
            name='academy_name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Назва Академії'),
        ),
        migrations.AddField(
            model_name='education',
            name='city_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='education',
            name='city_name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='education',
            name='profession_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Професія'),
        ),
        migrations.AddField(
            model_name='education',
            name='profession_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Професія'),
        ),
    ]
