# Generated by Django 4.2.6 on 2023-10-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_education_academy_name_en_education_academy_name_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_language', models.CharField(max_length=100, verbose_name='Мова програмування')),
                ('name_language_uk', models.CharField(max_length=100, null=True, verbose_name='Мова програмування')),
                ('name_language_en', models.CharField(max_length=100, null=True, verbose_name='Мова програмування')),
            ],
            options={
                'verbose_name_plural': 'Мова програмування',
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='academy_name',
            field=models.CharField(max_length=100, verbose_name='Назва Академії'),
        ),
        migrations.AlterField(
            model_name='education',
            name='academy_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва Академії'),
        ),
        migrations.AlterField(
            model_name='education',
            name='academy_name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва Академії'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, verbose_name='Навик')),
                ('skill_uk', models.CharField(max_length=100, null=True, verbose_name='Навик')),
                ('skill_en', models.CharField(max_length=100, null=True, verbose_name='Навик')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language', verbose_name='Мова програмування')),
            ],
            options={
                'verbose_name_plural': 'Навик',
            },
        ),
    ]
